# Generated by Django 5.2.9 on 2026-01-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fcm_token',
            field=models.TextField(blank=True, help_text='Firebase Cloud Messaging Token for Push Notifications', null=True),
        ),
    ]
