# Generated by Django 5.2.9 on 2026-01-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_image_expense_items_alter_expense_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
