# Generated by Django 5.2.9 on 2026-01-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='family_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
