# Generated by Django 5.2.9 on 2025-12-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
